[project]
name = "securitycore"
version = "1.1.1"
description = "Modular library for analysis, data protection, and validation"
authors = [
    {name = "Mihhail327",email = "mixa-amr@hotmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["cryptography (>=46.0.5,<47.0.0)", "pydantic (>=2.12.5,<3.0.0)"]

keywords = ["security", "cryptography", "validation", "xss-protection", "audit"]

[project.urls]
Homepage = "https://github.com/Mihhail327/SecurityCore"
Repository = "https://github.com/Mihhail327/SecurityCore"
Issues = "https://github.com/Mihhail327/SecurityCore/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.15.2,<0.16.0)",
    "pytest (>=9.0.2,<10.0.0)"
]
